projects:
  meetable:
    schemaPath: amplify/backend/api/meetable/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        maxDepth: 5
extensions:
  amplify:
    version: 3
