/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:8ff2f4f6-5488-4288-891a-7bbe52c81f7c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_35HLkYBt4",
    "aws_user_pools_web_client_id": "387b9tvkrq7ec472odu23hnqo9",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://huypok3oynayjg563wjvakzhsq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
