# This is a basic workflow to help you get started with Actions

name: Lintcheck preview

# Controls when the action will run. 
on: [pull_request]
defaults:
  run:
    working-directory: meetable-app
jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Cache Node Modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-	
            ${{ runner.os }}-build-	
            ${{ runner.os }}-
      - name: Install Packages
        run: npm install
      - name: Check Lint
        run: npm run lint
      - name: Test
        run: npm run test